// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmjwyibfnetfadbmgzop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptand5aWJmbmV0ZmFkYm1nem9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTE0OTgsImV4cCI6MjA3MDE2NzQ5OH0.55kPQYHOLWK8wVxditW_kS6lnMsW0r5EiS7EzARyP0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});